receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlphttp:
    endpoint: "https://5cd6-46-219-25-130.ngrok-free.app:443"
  logging:
    verbosity: detailed
    sampling_initial: 11
    sampling_thereafter: 2000
processors:
  batch:
  spanmetrics:
    metrics_exporter: otlphttp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
